### ISSUE TITLE
Issue getting int from cuda version

### ISSUE THREAD

**Issue by Jesse-Cachai** [zhangp365/comfyUI_docker#1]
Running this container in a microk8s cluster, I recently had issues getting it to start with it  giving this error:
ValueError: invalid literal for int() with base 10: '26+cu118'

I can give the traceback below:
Using xformers attention
Traceback (most recent call last):
  File "/app/main.py", line 132, in <module>
    import execution
  File "/app/execution.py", line 13, in <module>
    import nodes
  File "/app/nodes.py", line 22, in <module>
    import comfy.diffusers_load
  File "/app/comfy/diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "/app/comfy/sd.py", line 19, in <module>
    from . import clip_vision
  File "/app/comfy/clip_vision.py", line 8, in <module>
    import comfy.model_patcher
  File "/app/comfy/model_patcher.py", line 32, in <module>
    import comfy.lora
  File "/app/comfy/lora.py", line 22, in <module>
    import comfy.model_base
  File "/app/comfy/model_base.py", line 29, in <module>
    import comfy.ldm.pixart.pixartms
  File "/app/comfy/ldm/pixart/pixartms.py", line 7, in <module>
    from .blocks import (
  File "/app/comfy/ldm/pixart/blocks.py", line 15, in <module>
    if int((xformers.__version__).split(".")[2]) >= 28:
ValueError: invalid literal for int() with base 10: '26+cu118'

Looks like maybe I need a version greater than or equal to 28 maybe?

**Comment by zhangp365** [comment]
yes, the original xformers version is '0.0.26',  if you update, according to the code, it should be above 0.0.28, and there are no letters in the version, like '+cu118'.

**Comment by Jesse-Cachai** [comment]
Ok thanks for your reply. Why might I be getting this error? Can I try to manually query and see what I should get? I'm not sure what I should do.

**Comment by zhangp365** [comment]
I checked this, actually, this is a bug from the comfyui update two days ago. so, maybe you can try a little old version:
docker pull zhangp365/comfyui:20241215

**Comment by Jesse-Cachai** [comment]
Hey, I forgot to respond but this worked beautifully. Thanks so much for the speedy reply!
